### ISSUE TITLE
OSX Native

### ISSUE THREAD

**Issue by narenpublic** [capacitor-community/electron#65]
Has anyone made a capacitor plugin that accesses native osx code via an electron app?  E.g. permission to access contacts or calendar? Is this possible?  thnx

**Comment by IT-MikeS** [comment]
Since `electron` is basically just `nodejs` and `chromium` you can use any node api's you want so things like `node-mac-contacts` will work (never tried the npm package so I cant speak to its quality but its a good example). With this in mind you can always write native code for OSX and then call it from node to get a result, or even make it into a native module.

**Comment by narenpublic** [comment]
Thanks again. This was super helpful.
